# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xExDA-bqM1wyiriY0qpubOiyDeSAEBji
"""

import kagglehub
import os
path = kagglehub.dataset_download("haseebindata/student-performance-predictions")
print(f"Downloaded dataset path: {path}")
print(f"Contents of the downloaded directory: {os.listdir(path)}")
import pandas as pd
df = pd.read_csv(path + "/student_performance_updated_1000.csv")
df.head()

df.info()

df = df.drop_duplicates()

df = df.dropna()

dt_clean = df.isnull().sum()

"""NORMALISATION"""

df.columns

import scipy.stats as stats

# Convert 'Gender' column to numerical representation
# Assuming 'Male' and 'Female' are the primary categories.
gender_mapping = {'Male': 0, 'Female': 1}
df['Gender'] = df['Gender'].map(gender_mapping)

# Now apply z-score to the numerical 'Gender' column
df['Gender'] = stats.zscore(df['Gender'])

df_encoded = pd.get_dummies(df, columns=['ParentalSupport', 'Online Classes Taken'])
display(df_encoded.head())

X = df_encoded.drop(['FinalGrade', 'Name'], axis=1)
y = df_encoded['FinalGrade']

X.head()

"""TRAIN TEST SPLIT"""

import seaborn as sns
sns.kdeplot(df['FinalGrade'])

import seaborn as sns
sns.kdeplot(df['Attendance (%)'])

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""MODEL TRAINING"""

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
X = df_encoded.drop(['FinalGrade', 'Name'], axis=1)
y = df_encoded['FinalGrade']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
df_clf=DecisionTreeRegressor()
df_clf.fit(X_train,y_train)

df_pred=df_clf.predict(X_test)
df_acc=accuracy_score(y_test,df_pred)
print(df_acc)

df_rf=RandomForestRegressor()
df_rf.fit(X_train,y_train)

from sklearn.metrics import r2_score
df_rf_pred=df_rf.predict(X_test)
df_rf_acc=r2_score(y_test,df_rf_pred)
print(df_rf_acc)



"""MODEL SAVING"""

import pickle
with open ('df_model.pkl','wb') as f:
    pickle.dump(df_clf,f)
print("Model saved succesfully")

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
X = df_encoded.drop(['FinalGrade', 'Name'], axis=1)
y = df_encoded['FinalGrade']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
df_clf=DecisionTreeRegressor()
df_clf.fit(X_train,y_train)

df_pred=df_clf.predict(X_test)
df_acc=accuracy_score(y_test,df_pred)
print(df_acc)

df_rf=RandomForestRegressor()
df_rf.fit(X_train,y_train)

from sklearn.metrics import r2_score
df_rf_pred=df_rf.predict(X_test)
df_rf_acc=r2_score(y_test,df_rf_pred)
print(df_rf_acc)

import pickle
with open ('df_model.pkl','wb') as f:
    pickle.dump(df_clf,f)
print("Model saved succesfully")

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split
X = df_encoded.drop(['FinalGrade', 'Name'], axis=1)
y = df_encoded['FinalGrade']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
df_clf=DecisionTreeRegressor()
df_clf.fit(X_train,y_train)

df_pred=df_clf.predict(X_test)
df_acc=accuracy_score(y_test,df_pred)
print(df_acc)

df_rf=RandomForestRegressor()
df_rf.fit(X_train,y_train)

from sklearn.metrics import r2_score
df_rf_pred=df_rf.predict(X_test)
df_rf_acc=r2_score(y_test,df_rf_pred)
print(df_rf_acc)

import pickle
with open ('df_model.pkl','wb') as f:
    pickle.dump(df_clf,f)
print("Model saved succesfully")
